### ISSUE TITLE
Break of advanced search with the integration

### ISSUE THREAD

**Issue by iwkse** [cetra3/etherpad-alfresco#2]
I've been testing this with alfresco 5.0.c, a fresh clean installation.
When trying to use the Aikau Faceted Search Page it stops working raising an error.
It does not seem to be related to the CSRF configuration as I dropped completely the configuration and the error is still there.

**Comment by iwkse** [comment]
I've tested with 4.2.f and I can reproduce it as well.
HTH

**Comment by cetra3** [comment]
Yep, it's a bug within Alfresco which I've exposed by resolving another bug!

Line 153 of `js/alfresco/services/SearchService.js` reads:

```
var url = AlfConstants.PROXY_URI + "slingshot/search/";
```

This should read:

```
var url = AlfConstants.PROXY_URI + "slingshot/search";
```

Same with `js/alfresco/services/SearchService-min.js`

You can manually edit these files as a workaround.

To sort this out though properly would be:
- Raise a bug with Alfresco to fix their bug properly.  It's actually a bug within spring framework.
- Create a more robust workaround here.

**Comment by cetra3** [comment]
Should be fixed by this commit: https://github.com/cetra3/etherpad-alfresco/commit/3dcb134f65e7b31b644b9514aca6ea71c09b7e16

**Comment by iwkse** [comment]
Hi @cetra3 
I can confirm it works nice on 4.2.f!
But it still raises an error on 5.0.c. I will try to follow your advice about workarounding it and let you know
thanks for now

**Comment by cetra3** [comment]
Hi @iwkse, that's great!

I'm still curious as to why it's not working well on 5.0.c.

On your browser, if you open up dev tools, are you seeing a 404 error when you try and perform a search request?  That was the issue I was seeing and I worked around with this patch.  Requests to `/share/proxy/slingshot/search/` weren't being loaded correctly.

**Comment by iwkse** [comment]
Hi @cetra3
exactly, I just get a 404 error. Maybe they changed something in 5.x and the patch doesn't work on it. But suretly it seems to be that the problem.
Should I fire a bug mainstream to Alfresco?

**Comment by iwkse** [comment]
@cetra3
It was a matter of cache..cleared and it works on 5.0.c as well

**Comment by cetra3** [comment]
No worries, I'll close this issue off!

**Comment by iwkse** [comment]
Hi @cetra3,
please can you comment that https://issues.alfresco.com/jira/browse/ALF-21251 if you work arounded the bug?

**Comment by cetra3** [comment]
The issue I have had raised is here, which relates to the share proxy behaviour:
https://issues.alfresco.com/jira/browse/MNT-13288

If they fix that bug though, then they will need to fix ALF-21251.  I can let them know.
