### ISSUE TITLE
Save back doesn't work on Alfresco 5

### ISSUE THREAD

**Issue by iwkse** [cetra3/etherpad-alfresco#4]
Hi @cetra3 
I've just discovered the save back button doesn't save on Alfresco 5 back to alfresco. The pad is up to date but the file preview in alfresco is not.

Possible CSRF attack noted when comparing token in session and request header. Request: POST /share/proxy/alfresco/api/node/workspace/SpacesStore/157c87e1-68f4-4715-8c61-2beb7decabc2/formprocessor

Do you have the opportunity to reproduce it on 5?
thanks

**Comment by iwkse** [comment]
This is what I get while clicking on Save Back
/share/proxy/alfresco/api/node/workspace/SpacesStore/157c87e1-68f4-4715-8c61-2beb7decabc2/formprocessor HTTP/1.1" 500

**Comment by cetra3** [comment]
Need to include the CSRF headers on Submission

**Comment by iwkse** [comment]
I've tried following this page, http://docs.alfresco.com/4.1/concepts/csfr-policy.html but it doesn't seem to work for me.
Should it be inserted here? etherpad.js

```
  request.post(Alfresco.constants.PROXY_URI_RELATIVE + "api/node/" + nodeRef.replace("://", "/") + "/formprocessor", {
            headers: {
                "Content-Type" : "application/json",
            },
            data : JSON.stringify({
               prop_cm_content : htmlData.substring(beginHtml, endHtml + 7)
            })
         }).then(function() {
            Alfresco.util.PopupManager.displayMessage({"text": "Update Submitted"});
         });
```

**Comment by cetra3** [comment]
Yep, we need to add the header the post request, as it isn't doing it at the moment.

**Comment by iwkse** [comment]
I've tried but I guess I didn't add it right. I guess it should be added in the
headers: {
}
bit..but I don't know how :-)

**Comment by cetra3** [comment]
I've committed a fix for this: https://github.com/cetra3/etherpad-alfresco/commit/97477fd4d2841fe5194b32e6a5b6215ea43d94ec

Make sure you refresh your cache etc... when testing.

**Comment by iwkse** [comment]
Tested and works fine!
Thanks

**Comment by cetra3** [comment]
Ah! Good news!

**Comment by iwkse** [comment]
I'm adding some other small things, i will send a patch when I finish, is mainly about localizing strings. There's one thing I was not yet able to find, how to localize messages in etherpad.js in META-INF/components/etherpad.
I've appended strings in the original properties file but it doesn't seem to work. I've used msg.get("etherpad.myString") to refer to it.
Maybe to open a separate issue for this?

**Comment by cetra3** [comment]
Yeah open a separate issue for localization and we can work through it.
